extraction:
  cpp:
    after_prepare: 
      - python report.py 10
  cobol:
    after_prepare: 
      - python report.py 10
  csharp:
    after_prepare: 
      - python report.py 10
  java:
    after_prepare: 
      - python report.py 10
  javascript:
    after_prepare: 
      - python report.py 10
  python:
    after_prepare: 
      - python report.py 10
